import numpy as np

DOMAIN_WIDTH = 300
DOMAIN_HEIGHT = 600

PARTICLE_MASS = 5
ISOTROPIC_EXPONENT = 20
BASE_DENSITY = 3
SMOOTHING_LENGTH = 5
DYNAMIC_VISCOSITY = 0.5
DAMPING_COEFFICIENT = - 0.3
CONSTANT_FORCE = np.array([[0.0, 0.1]])

TIME_STEP_LENGTH = 0.01
SCATTER_DOT_SIZE = 5

DOMAIN_X_LIM = np.array([
    SMOOTHING_LENGTH,
    DOMAIN_WIDTH - SMOOTHING_LENGTH
])
DOMAIN_Y_LIM = np.array([
    SMOOTHING_LENGTH,
    DOMAIN_HEIGHT - SMOOTHING_LENGTH
])

NORMALIZATION_DENSITY = ((315 * PARTICLE_MASS) / (64 * np.pi * SMOOTHING_LENGTH ** 9))
NORMALIZATION_PRESSURE_FORCE = (-(45 * PARTICLE_MASS) / (np.pi * SMOOTHING_LENGTH ** 6))
NORMALIZATION_VISCOUS_FORCE = ((45 * DYNAMIC_VISCOSITY * PARTICLE_MASS) / (np.pi * SMOOTHING_LENGTH ** 6))